#!/usr/bin/env python3
"""Build docs/jira/README.md and the totals block of every daily file.

    scripts/build_journal_index.py JOURNAL_DIR          write the index and daily totals
    scripts/build_journal_index.py JOURNAL_DIR --check  exit 1 if anything is stale

Index: reads each `<KEY>.md` in JOURNAL_DIR for the `# KEY — Summary` title, the
optional `Status:` line and the newest `### YYYY-MM-DD` heading.

Daily totals: reads the table in each JOURNAL_DIR/daily/YYYY-MM-DD.md and rewrites the
block between the totals markers at the end of the file:
  worked    clock time covered by the rows' Time spans, overlaps counted once
  logged    sum of the durations in ✅ Logged cells
  unlogged  clock time covered by rows still ⏳

Everything this script writes is generated, so never edit it by hand.
"""
import argparse
import re
import sys
from pathlib import Path

BANNER = "<!-- generated by jira-plugin/scripts/build_journal_index.py. Do not edit by hand. -->"
TOTALS_START = "<!-- totals:start · generated by jira-plugin/scripts/build_journal_index.py -->"
TOTALS_END = "<!-- totals:end -->"
KEY_FILE = re.compile(r"^[A-Z][A-Z0-9]+-\d+\.md$")
DAILY_FILE = re.compile(r"^\d{4}-\d{2}-\d{2}\.md$")
TITLE = re.compile(r"^#\s+([A-Z][A-Z0-9]+-\d+)\s+[—–-]\s+(.+?)\s*$")
STATUS = re.compile(r"^Status:\s*([^·\n]+)", re.M)
DAY = re.compile(r"^###\s+(\d{4}-\d{2}-\d{2})", re.M)
TICKET_CELL = re.compile(r"^\[?[A-Z][A-Z0-9]+-\d+\b")
SPAN = re.compile(r"^\s*(\d{1,2}):(\d{2})\s*[–—-]\s*(\d{1,2}):(\d{2})\s*$")
CELL_SPLIT = re.compile(r"(?<!\\)\|")
TOTALS_BLOCK = re.compile(re.escape(TOTALS_START) + r".*?" + re.escape(TOTALS_END) + r"\n?", re.S)
RECENT_DAYS = 7


# ---------------------------------------------------------------- durations

def fmt_minutes(minutes):
    hours, mins = divmod(int(minutes), 60)
    if hours and mins:
        return "%dh %dm" % (hours, mins)
    return "%dh" % hours if hours else "%dm" % mins


def parse_logged(cell):
    """`✅ 1h 30m · worklog 11502` -> 90. Anything not ticked -> None."""
    if "✅" not in cell:
        return None
    amount = cell.split("·")[0]
    hours = sum(int(h) for h in re.findall(r"(\d+)\s*h", amount))
    mins = sum(int(m) for m in re.findall(r"(\d+)\s*m", amount))
    return hours * 60 + mins


def parse_span(cell):
    """`11:33–12:19` -> (693, 739) minutes since midnight, or None."""
    m = SPAN.match(cell)
    if not m:
        return None
    start = int(m.group(1)) * 60 + int(m.group(2))
    end = int(m.group(3)) * 60 + int(m.group(4))
    return (start, end) if end > start else None


def union_minutes(spans):
    total, current_start, current_end = 0, None, None
    for start, end in sorted(spans):
        if current_end is None or start > current_end:
            if current_end is not None:
                total += current_end - current_start
            current_start, current_end = start, end
        else:
            current_end = max(current_end, end)
    if current_end is not None:
        total += current_end - current_start
    return total


# ---------------------------------------------------------------- daily files

def read_daily_rows(text):
    rows = []
    for line in text.splitlines():
        if not line.startswith("| "):
            continue
        cells = [c.strip() for c in CELL_SPLIT.split(line.strip().strip("|"))]
        # A ticket row: first cell is a key, linked to its journal or bare when it has none.
        if len(cells) < 6 or not TICKET_CELL.match(cells[0]):
            continue
        rows.append({"time": cells[2], "logged": cells[5]})
    return rows


def daily_totals(text):
    rows = read_daily_rows(text)
    spans = [parse_span(r["time"]) for r in rows]
    valid = [s for s in spans if s]
    pending = [s for s, r in zip(spans, rows) if s and "✅" not in r["logged"]]
    logged = [parse_logged(r["logged"]) for r in rows]
    worked = union_minutes(valid)
    return {
        "rows": len(rows),
        "worked": worked,
        "overlap": sum(e - s for s, e in valid) - worked,
        "logged": sum(x for x in logged if x is not None),
        "unlogged": union_minutes(pending),
        "pending_rows": sum(1 for r in rows if "✅" not in r["logged"]),
        "untimed_rows": sum(1 for s in spans if s is None),
    }


def totals_block(t):
    pending = " · %d row%s ⏳" % (t["pending_rows"], "" if t["pending_rows"] == 1 else "s") if t["pending_rows"] else ""
    lines = [
        TOTALS_START,
        "",
        "| Worked | Logged | Unlogged |",
        "|---|---|---|",
        "| %s | %s | %s%s |" % (fmt_minutes(t["worked"]), fmt_minutes(t["logged"]), fmt_minutes(t["unlogged"]), pending),
    ]
    notes = []
    if t["overlap"]:
        notes.append("Overlapping rows counted once (%s overlap)." % fmt_minutes(t["overlap"]))
    if t["untimed_rows"]:
        notes.append("%d row%s without a valid `HH:MM–HH:MM` time %s not counted as worked."
                     % (t["untimed_rows"], "" if t["untimed_rows"] == 1 else "s",
                        "is" if t["untimed_rows"] == 1 else "are"))
    if notes:
        lines += [""] + notes
    lines += ["", TOTALS_END, ""]
    return "\n".join(lines)


def with_totals(text):
    block = totals_block(daily_totals(text))
    stripped = TOTALS_BLOCK.sub("", text).rstrip("\n")
    return stripped + "\n\n" + block


# ---------------------------------------------------------------- index

def ticket_sort_key(key):
    project, number = key.split("-")
    return project, int(number)


def read_journal(path):
    text = path.read_text(encoding="utf-8")
    first = text.splitlines()[0] if text else ""
    title = TITLE.match(first)
    status = STATUS.search(text)
    days = DAY.findall(text)
    return {
        "key": path.stem,
        "summary": (title.group(2) if title else "(no title line)").replace("|", "\\|"),
        "status": status.group(1).strip() if status else "—",
        "last": max(days) if days else "—",
        "file": path.name,
    }


def build_index(journal_dir, daily):
    journals = [read_journal(p) for p in sorted(journal_dir.glob("*.md")) if KEY_FILE.match(p.name)]
    journals.sort(key=lambda j: ticket_sort_key(j["key"]))
    journals.sort(key=lambda j: j["last"] if j["last"] != "—" else "", reverse=True)

    lines = [
        "# Jira journal index",
        "",
        BANNER,
        "",
        "One line per ticket journal, most recently worked first. `Status` is as last written in the",
        "journal, not live from Jira.",
        "",
    ]
    if daily:
        lines += ["## Recent days", "", "| Day | Worked | Logged | Unlogged |", "|---|---|---|---|"]
        for day, totals in daily[:RECENT_DAYS]:
            lines.append("| [%s](daily/%s.md) | %s | %s | %s |" % (
                day, day, fmt_minutes(totals["worked"]), fmt_minutes(totals["logged"]), fmt_minutes(totals["unlogged"])))
        lines += ["", "## Tickets", ""]
    lines += ["| Ticket | Summary | Status (journal) | Last worked |", "|---|---|---|---|"]
    lines += ["| [%s](%s) | %s | %s | %s |" % (j["key"], j["file"], j["summary"], j["status"], j["last"])
              for j in journals]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- main

def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("journal_dir", type=Path)
    parser.add_argument("--check", action="store_true", help="exit 1 if the index or any daily totals are stale")
    args = parser.parse_args()

    if not args.journal_dir.is_dir():
        sys.exit("not a directory: %s" % args.journal_dir)

    writes = {}
    daily = []
    daily_dir = args.journal_dir / "daily"
    if daily_dir.is_dir():
        for path in sorted((p for p in daily_dir.glob("*.md") if DAILY_FILE.match(p.name)), reverse=True):
            text = path.read_text(encoding="utf-8")
            updated = with_totals(text)
            daily.append((path.stem, daily_totals(updated)))
            writes[path] = (text, updated)

    index_path = args.journal_dir / "README.md"
    current = index_path.read_text(encoding="utf-8") if index_path.exists() else None
    writes[index_path] = (current, build_index(args.journal_dir, daily))

    stale = [p for p, (old, new) in writes.items() if old != new]
    if args.check:
        for p in stale:
            print("stale: %s" % p)
        print("up to date" if not stale else "%d file(s) stale" % len(stale))
        sys.exit(1 if stale else 0)

    for p in stale:
        p.write_text(writes[p][1], encoding="utf-8")
        print("wrote %s" % p)
    if not stale:
        print("up to date")


if __name__ == "__main__":
    main()
