#!/usr/bin/env python3
"""Build docs/jira/README.md, the index of every ticket journal.

    scripts/build_journal_index.py JOURNAL_DIR          write JOURNAL_DIR/README.md
    scripts/build_journal_index.py JOURNAL_DIR --check  exit 1 if README.md is stale

Reads each `<KEY>.md` in JOURNAL_DIR: the `# KEY — Summary` title, the optional
`Status:` line and the newest `### YYYY-MM-DD` heading. Links the most recent daily
files from JOURNAL_DIR/daily/. The output is generated, so never edit it by hand.
"""
import argparse
import re
import sys
from pathlib import Path

BANNER = "<!-- generated by jira-plugin/scripts/build_journal_index.py. Do not edit by hand. -->"
KEY_FILE = re.compile(r"^[A-Z][A-Z0-9]+-\d+\.md$")
TITLE = re.compile(r"^#\s+([A-Z][A-Z0-9]+-\d+)\s+[—–-]\s+(.+?)\s*$")
STATUS = re.compile(r"^Status:\s*([^·\n]+)", re.M)
DAY = re.compile(r"^###\s+(\d{4}-\d{2}-\d{2})", re.M)
RECENT_DAYS = 7


def ticket_sort_key(key):
    project, number = key.split("-")
    return project, int(number)


def read_journal(path):
    text = path.read_text(encoding="utf-8")
    first = text.splitlines()[0] if text else ""
    title = TITLE.match(first)
    key = path.stem
    summary = title.group(2) if title else "(no title line)"
    status = STATUS.search(text)
    days = DAY.findall(text)
    return {
        "key": key,
        "summary": summary.replace("|", "\\|"),
        "status": status.group(1).strip() if status else "—",
        "last": max(days) if days else "—",
        "file": path.name,
    }


def build(journal_dir):
    journals = [read_journal(p) for p in sorted(journal_dir.glob("*.md")) if KEY_FILE.match(p.name)]
    # Newest work first; tickets never dated sink to the bottom, then by key.
    journals.sort(key=lambda j: ticket_sort_key(j["key"]))
    journals.sort(key=lambda j: j["last"] if j["last"] != "—" else "", reverse=True)

    daily_dir = journal_dir / "daily"
    days = sorted((p.stem for p in daily_dir.glob("????-??-??.md")), reverse=True) if daily_dir.is_dir() else []

    lines = [
        "# Jira journal index",
        "",
        BANNER,
        "",
        "One line per ticket journal, most recently worked first. `Status` is as last written in the",
        "journal, not live from Jira.",
        "",
    ]
    if days:
        recent = " · ".join("[%s](daily/%s.md)" % (d, d) for d in days[:RECENT_DAYS])
        lines += ["**Recent days:** " + recent, ""]
    lines += ["| Ticket | Summary | Status (journal) | Last worked |", "|---|---|---|---|"]
    lines += ["| [%s](%s) | %s | %s | %s |" % (j["key"], j["file"], j["summary"], j["status"], j["last"])
              for j in journals]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("journal_dir", type=Path)
    parser.add_argument("--check", action="store_true", help="exit 1 if README.md is stale")
    args = parser.parse_args()

    if not args.journal_dir.is_dir():
        sys.exit("not a directory: %s" % args.journal_dir)

    target = args.journal_dir / "README.md"
    content = build(args.journal_dir)
    if args.check:
        stale = not target.exists() or target.read_text(encoding="utf-8") != content
        print("stale" if stale else "up to date")
        sys.exit(1 if stale else 0)

    target.write_text(content, encoding="utf-8")
    print("wrote %s" % target)


if __name__ == "__main__":
    main()
