#!/usr/bin/env python3
"""Compose core/ into every harness. Run after editing anything under core/.

    scripts/sync.py                 regenerate harness/claude and harness/cursor
    scripts/sync.py --check         exit 1 if a harness is stale, changing nothing
    scripts/sync.py --install DIR   also install into DIR/.claude and DIR/.cursor

core/ is the single source of truth. Everything this script writes is generated, so
never hand-edit a generated file: the next sync overwrites it.
"""
import argparse
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORE, HARNESS = ROOT / "core", ROOT / "harness"
BANNER = "<!-- generated by scripts/sync.py from core/. Do not edit by hand. -->"

# knowledge file -> the sentence that sends a reader there
ROUTES = [
    ("reading.md",     "Fetch an issue, search, list comments or worklogs"),
    ("writing.md",     "Post or edit a comment, log time, transition, edit fields"),
    ("workflows.md",   "Follow a task end to end"),
    ("journal.md",     "Write the per-ticket journal"),
    ("conventions.md", "Know this project's keys, branches and statuses"),
]


def identity():
    text = (CORE / "identity.yaml").read_text()
    out = {}
    for key in ("name", "one_liner", "triggers", "gotcha"):
        m = re.search(r"^%s:\s*(.+)$" % key, text, re.M)
        if not m:
            sys.exit("core/identity.yaml is missing %r" % key)
        out[key] = m.group(1).strip()
    return out


def body(path):
    """File contents with any YAML frontmatter stripped."""
    t = (CORE / path).read_text()
    return re.sub(r"\A---\n.*?\n---\n+", "", t, flags=re.S).strip()


def build_claude_skill(ident):
    routes = "\n".join("| %s | [references/%s](references/%s) |" % (label, f, f)
                       for f, label in ROUTES)
    return f"""---
name: {ident['name']}
description: {ident['one_liner']} {ident['triggers']}
---

{BANNER}

# Jira

Jira runs through the `jira` MCP server. Never write raw `curl` against the Jira API.

## Rules that always apply

{body('rules.md')}

## Where to look

| You need to | Read |
| --- | --- |
{routes}

## The one gotcha to remember

{ident['gotcha']} Full explanation in
[references/writing.md](references/writing.md).

## Resolving the issue key

{body('key-resolution.md')}
"""


def build_cursor_rule(ident):
    """Cursor rules have no progressive disclosure, so everything is inlined."""
    parts = [f"""---
description: {ident['one_liner']} {ident['triggers']}
alwaysApply: false
---

{BANNER}

# Jira

Jira runs through the `jira` MCP server. Never write raw `curl` against the Jira API.

## Rules that always apply

{body('rules.md')}

## Resolving the issue key

{body('key-resolution.md')}
"""]
    for fname, _ in ROUTES:
        parts.append(body("knowledge/" + fname))
    return "\n\n---\n\n".join(parts) + "\n"


def targets(ident):
    """Every generated path mapped to its content."""
    out = {HARNESS / "claude/skills/jira/SKILL.md": build_claude_skill(ident),
           HARNESS / "cursor/rules/jira.mdc": build_cursor_rule(ident)}
    for fname, _ in ROUTES:
        out[HARNESS / "claude/skills/jira/references" / fname] = (CORE / "knowledge" / fname).read_text()
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="report staleness, write nothing")
    ap.add_argument("--install", metavar="DIR", help="also install into a project")
    a = ap.parse_args()

    plan = targets(identity())
    stale = [p for p, c in plan.items() if not p.exists() or p.read_text() != c]

    if a.check:
        for p in stale:
            print("STALE  %s" % p.relative_to(ROOT))
        print("%d of %d generated file(s) out of date" % (len(stale), len(plan)))
        return 1 if stale else 0

    for p, c in plan.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(c)
    print("synced %d file(s) from core/ (%d changed)" % (len(plan), len(stale)))

    if a.install:
        proj = Path(a.install).expanduser().resolve()
        cl = HARNESS / "claude"
        for src, dst in ((cl / "skills/jira", proj / ".claude/skills/jira"),
                         (cl / "commands",   proj / ".claude/commands/jira")):
            shutil.rmtree(dst, ignore_errors=True)
            shutil.copytree(src, dst)
            print("  ->", dst)
        for src, dst in ((cl / "agents/jira.md", proj / ".claude/agents/jira.md"),
                         (cl / ".mcp.json",      proj / ".mcp.json"),
                         (HARNESS / "cursor/rules/jira.mdc", proj / ".cursor/rules/jira.mdc")):
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy(src, dst)
            print("  ->", dst)
    return 0


if __name__ == "__main__":
    sys.exit(main())
